# Global settings applied to the whole site.
[build]
  base    = ""
  publish = "public"
  command = "gulp build"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production.environment]
  HUGO_VERSION = "0.27.1"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview.environment]
  HUGO_VERSION = "0.27.1"

# Branch Deploy context: All Branch Deploys
# will inherit these settings.
[context.branch-deploy.environment]
  HUGO_VERSION = "0.27.1"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
###
# [context.branch-deploy]
#   command = "make staging"

# Specific branch context: Deploys from this branch
# will take these settings and override their
# current ones.
###
# [context.feature]
#   command = "make feature"

# [context."features/branch"]
#   command = "gulp"
